### ISSUE TITLE
Wire.begin Called Within .begin Method

### ISSUE THREAD

**Issue by oclyke** [sparkfun/SparkFun_BME280_Arduino_Library#46]
Mostly a style issue - SparkFun libraries now usually leave the I2C / SPI begin methods to be called at the sketch level so that configuration parameters can be respected.

**Comment by nseidle** [comment]
Yep. We were holding off because the age of this library and the amount of pre-existing code that may break. I changed the examples in [2018](https://github.com/sparkfun/SparkFun_BME280_Arduino_Library/commit/715f7bc5acec08fa9b3bd7c09f7fbd8b3daee644#diff-6f54e2564bad1c01518721012db4647423489efcd212d2e3e44b022521661bbd) so hopefully we won't break too much with upcoming release.
